SET search_path TO movies_data;

-- Movie ID: 11
INSERT INTO movie (movie_id, title, release_date, duration_minutes, rating, synopsis, overview, adult, budget, revenue, tagline) VALUES (11, 'Star Wars', '1977-05-25', 121, 8.2, 'Princess Leia is captured and held hostage by the evil Imperial forces in their effort to take over the galactic Empire. Venturesome Luke Skywalker and dashing captain Han Solo team together with the loveable robot duo R2-D2 and C-3PO to rescue the beautiful princess and restore peace and justice in the Empire.', 'Princess Leia is captured and held hostage by the evil Imperial forces in their effort to take over the galactic Empire. Venturesome Luke Skywalker and dashing captain Han Solo team together with the loveable robot duo R2-D2 and C-3PO to rescue the beautiful princess and restore peace and justice in the Empire.', FALSE, 11000000, 775398007, 'A long time ago in a galaxy far, far away...');

-- Movie ID: 550
INSERT INTO movie (movie_id, title, release_date, duration_minutes, rating, synopsis, overview, adult, budget, revenue, tagline) VALUES (550, 'Fight Club', '1999-10-15', 139, 8.438, 'A ticking-time-bomb insomniac and a slippery soap salesman channel primal male aggression into a shocking new form of therapy. Their concept catches on, with underground "fight clubs" forming in every town, until an eccentric gets in the way and ignites an out-of-control spiral toward oblivion.', 'A ticking-time-bomb insomniac and a slippery soap salesman channel primal male aggression into a shocking new form of therapy. Their concept catches on, with underground "fight clubs" forming in every town, until an eccentric gets in the way and ignites an out-of-control spiral toward oblivion.', FALSE, 63000000, 100853753, 'Mischief. Mayhem. Soap.');

-- Movie ID: 13
INSERT INTO movie (movie_id, title, release_date, duration_minutes, rating, synopsis, overview, adult, budget, revenue, tagline) VALUES (13, 'Forrest Gump', '1994-06-23', 142, 8.466, 'A man with a low IQ has accomplished great things in his life and been present during significant historic events—in each case, far exceeding what anyone imagined he could do. But despite all he has achieved, his one true love eludes him.', 'A man with a low IQ has accomplished great things in his life and been present during significant historic events—in each case, far exceeding what anyone imagined he could do. But despite all he has achieved, his one true love eludes him.', FALSE, 55000000, 677387716, 'The world will never be the same once you''ve seen it through the eyes of Forrest Gump.');

-- Movie ID: 120
INSERT INTO movie (movie_id, title, release_date, duration_minutes, rating, synopsis, overview, adult, budget, revenue, tagline) VALUES (120, 'The Lord of the Rings: The Fellowship of the Ring', '2001-12-18', 179, 8.424, 'Young hobbit Frodo Baggins, after inheriting a mysterious ring from his uncle Bilbo, must leave his home in order to keep it from falling into the hands of its evil creator. Along the way, a fellowship is formed to protect the ringbearer and make sure that the ring arrives at its final destination: Mt. Doom, the only place where it can be destroyed.', 'Young hobbit Frodo Baggins, after inheriting a mysterious ring from his uncle Bilbo, must leave his home in order to keep it from falling into the hands of its evil creator. Along the way, a fellowship is formed to protect the ringbearer and make sure that the ring arrives at its final destination: Mt. Doom, the only place where it can be destroyed.', FALSE, 93000000, 871368364, 'One ring to rule them all.');

